/**
 * Common Constants
 * Shared constants used across multiple modules
 */

export const MILLISECONDS_PER_SECOND = 1000;
export const SECONDS_PER_MINUTE = 60;
export const MINUTES_PER_HOUR = 60;
export const MILLISECONDS_PER_MINUTE =
  SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;
export const MILLISECONDS_PER_HOUR = MINUTES_PER_HOUR * MILLISECONDS_PER_MINUTE;
export const ONE_SECOND_IN_MS = MILLISECONDS_PER_SECOND;
export const ONE_MINUTE_IN_MS = MILLISECONDS_PER_MINUTE;
export const FIVE_MINUTES_IN_MS = 5 * ONE_MINUTE_IN_MS;
export const TEN_MINUTES_IN_MS = 10 * ONE_MINUTE_IN_MS;
export const FIFTEEN_MINUTES_IN_MS = 15 * ONE_MINUTE_IN_MS;
export const ONE_HOUR_IN_MS = MILLISECONDS_PER_HOUR;
export const PARSE_INT_RADIX = 10;
export const RANDOM_STRING_BASE = 36;
export const RANDOM_STRING_SLICE_START = 2;
export const RANDOM_BYTES_SIZE = 32;
