import { type ReactNode } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { TestAuthBypass } from '@/components/test-auth-bypass/TestAuthBypass';
import { ReduxProvider } from '@/lib/redux/ReduxProvider';
import { SessionProvider } from '@/lib/auth/SessionProvider';
import { MsalProvider } from '@/lib/auth/MsalProvider';
import { TanStackQueryProvider } from '@/lib/tanstack-query/provider';
import { WebVitalsReporter } from '@/components/WebVitalsReporter';
import { ThemeProvider } from '@/lib/theme/ThemeProvider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CR Project App',
  description: 'Generated by ReVamp',
};

const shouldBypassAuthForTests =
  process.env.NODE_ENV !== 'production' && process.env.BYPASS_AUTH === 'true';

if (shouldBypassAuthForTests) {
  console.info(
    '[Auth] Bypass authentication mode enabled (non-production only)',
  );
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TestAuthBypass isEnabled={shouldBypassAuthForTests} />
        <ThemeProvider>
          <WebVitalsReporter />
          <MsalProvider>
            <SessionProvider>
              <TanStackQueryProvider>
                <ReduxProvider>{children}</ReduxProvider>
              </TanStackQueryProvider>
            </SessionProvider>
          </MsalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
