import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReduxProvider } from '@/lib/redux/ReduxProvider';
import { SessionProvider } from '@/lib/auth/SessionProvider';
import { MsalProvider } from '@/lib/auth/MsalProvider';
import { TanStackQueryProvider } from '@/lib/tanstack-query/provider';
import { WebVitalsReporter } from '@/components/WebVitalsReporter';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CR Project App',
  description: 'Generated by ReVamp',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WebVitalsReporter />
        <MsalProvider>
          <SessionProvider>
            <TanStackQueryProvider>
              <ReduxProvider>{children}</ReduxProvider>
            </TanStackQueryProvider>
          </SessionProvider>
        </MsalProvider>
      </body>
    </html>
  );
}
